config/routes.rb
Rails.application.routes.draw do
  root to: 'parks#index'

  resources :parks, only: [:index, :show] do
    resources :reviews, only: [:create, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/park.rb
class Park < ApplicationRecord
  has_many :parks_states
  has_many :states, through: :parks_states
  has_many :reviews

  def self.by_state(state)
    if State.exists?(abbreviation: state)
      self
      .joins(:states)
			.where(states: { abbreviation: state })
    else
      self.all
    end
  end
end

app/models/parks_state.rb
class ParksState < ApplicationRecord
  belongs_to :park
  belongs_to :state
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :park
end

app/models/state.rb
class State < ApplicationRecord
  has_many :parks_states
  has_many :parks, through: :parks_states
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def index
    @parks = Park
      .paginate(page: params[:page])
      .includes(:states)
      .order(:full_name)
      .by_state(params[:state])
      .all

    @states = State.all.order(:abbreviation)
    @selected = params[:state]
  end

  def show
    @park = Park.includes(:states, :reviews).find(params[:id])
    @review = Review.new
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    park = Park.find(params[:park_id])
    park.reviews.create(review_params)

    @review = Review.new
    redirect_to park_path(park)
  end

  def edit
    @park = Park.find(params[:park_id])
    @review = Review.find(params[:id])
  end

  def update
    park = Park.find(params[:park_id])
    Review.find(params[:id]).update(review_params)

    @review = Review.new
    redirect_to park_path(park)
  end

  private
  def review_params
    params.require(:review).permit(:name, :review)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parks</title>
    <%= csrf_meta_tags %>

		
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		</head>
		
		<body>
    <nav>
		<%= link_to "Parks", parks_path %>
    </nav>
		<%= yield %>
  </body>
</html>

app/views/parks/index.html.erb
<h2>Parks</h2>

<%= will_paginate @parks %>

<div id='result'>my choice</div>

<h3>Search</h3>
<%= form_tag parks_path, method: :get do %>
  <%= select_tag(
    "state",
    options_from_collection_for_select(
      @states,
      "abbreviation",
      "abbreviation",
      @selected
    ),
		include_blank: "All", 
		id: "state_select"
  ) %>
  <%= submit_tag "Search" %>
<% end %>



<% @parks.each do |park| %>
  <div id="<%= park.api_id %>">
    <h3>
      <%= park.full_name %> - <%= park.states.map(&:abbreviation).join(", ") %>
    </h3>
    <%= link_to "View Park", park_path(park.id) %>
  </div>
<% end %>

<%= will_paginate @parks %>

app/views/parks/show.html.erb
<h2><%= @park.full_name %></h2>
<h4>Designation: <%= @park.designation %></h4>

<h3>Located In: <%= @park.states.map(&:abbreviation).join(", ") %></h3>

<h3>Description</h3>
<p><%= @park.description %></p>

<h3>Weather</h3>
<p><%= @park.weather_info %></p>

<h3>Directions</h3>
<p><%= @park.directions_info %></p>

<h3>More Information: </h3>
<ul>
  <li><%= link_to "Website", @park.url, { target: "_blank" } %></li>
  <li>
    <%= link_to "Directions", @park.directions_url, { target: "_blank" } %>
  </li>
</ul>

<h3>Reviews: </h3>

<ul>
  <% @park.reviews.each do |review| %>
    <li>
      <p>
        <strong><%= review.name %></strong>
        says... <%= review.review %> 
        <%= link_to "Edit Review", edit_park_review_path(@park, review) %>
      </p>
    </li>
  <% end %>
</ul>

<h4>Create Review</h4>
<%= render "reviews/form" %>

app/views/reviews/_form.html.erb
<%= form_for @review, url: park_reviews_path(@park) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :review %>
    <%= f.text_area :review %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h4>Edit Review</h4>
<%= form_for @review, url: park_review_path(@park, @review) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :review %>
    <%= f.text_area :review %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>